# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [3]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],    # creating DataFrame 
 'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],
 'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
 'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}
df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [5]:
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Price"] # to creat a column name Revenue by multiplying units_sold and price
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [9]:
df_sales[["Units_Sold", "Revenue"]].sum()  # total number of units sold and total revenue

Units_Sold      105
Revenue       16000
dtype: int64

In [10]:
df_sales[["Units_Sold", "Revenue"]].mean() # avg number of units sold and avg revenue

Units_Sold      11.666667
Revenue       1777.777778
dtype: float64

## Grouping Data

In [11]:
df_sales.groupby("Product")[["Units_Sold", "Revenue"]].sum() # grouped by product(unique values) and
                                                            # calculated the total Units_Sold and total Revenue for each product

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [14]:
df_sales.groupby("Region")[["Units_Sold", "Revenue"]].mean() # grouped by Region(unique values) and
                                                             # calculated the avg Units_Sold and total Revenue for each product

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [16]:
df_sales.groupby(["Product", "Region"])[["Units_Sold", "Revenue"]].sum() # grouped them by product and region and 
                                                                        # # calculated the total Units_Sold and total Revenue for the combination

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [18]:
df_sales.sort_values("Units_Sold") # sorting by units sold in ascending order

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [19]:
df_sales.sort_values("Revenue", ascending=False) # sorting by revenue in descending order

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [23]:
df_sales["Revenue_Rank"] = df_sales["Revenue"].rank(ascending=False) # Added a new column "Revenue_Rank in descending order
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [24]:
product_data = {'Product': ['A', 'B', 'C'],
 'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)

In [25]:
df_merged = pd.merge(df_sales, df_products, on="Product") # merged the existed data(df_sales) and the new data(df_products)
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [27]:
df_merged.groupby("Category")["Revenue"].sum() # grouped by category and total revenue by category

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64